# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Congestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timebin', models.DateTimeField(db_index=True)),
                ('magnitude', models.FloatField(default=0.0)),
                ('deviation', models.FloatField(default=0.0)),
                ('label', models.CharField(max_length=255)),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihr.ASN')),
            ],
        ),
        migrations.CreateModel(
            name='CongestionRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('timebin', models.DateTimeField()),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihr.ASN')),
            ],
        ),
        migrations.CreateModel(
            name='Forwarding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timebin', models.DateTimeField(db_index=True)),
                ('magnitude', models.FloatField(default=0.0)),
                ('resp', models.FloatField(default=0.0)),
                ('label', models.CharField(default='', max_length=255)),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihr.ASN')),
            ],
        ),
        migrations.CreateModel(
            name='ForwardingRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('timebin', models.DateTimeField()),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihr.ASN')),
            ],
        ),
    ]
