# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-05 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congestion_alarms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timebin', models.DateTimeField(db_index=True)),
                ('ip', models.CharField(db_index=True, max_length=64)),
                ('link', models.CharField(db_index=True, max_length=128)),
                ('medianrtt', models.FloatField(default=0.0)),
                ('diffMedian', models.FloatField(default=0.0)),
                ('deviation', models.FloatField(default=0.0)),
                ('nbProbes', models.IntegerField(default=0)),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihr.ASN')),
            ],
        ),
        migrations.CreateModel(
            name='Forwarding_alarms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timebin', models.DateTimeField(db_index=True)),
                ('ip', models.CharField(db_index=True, max_length=64)),
                ('correlation', models.FloatField(default=0.0)),
                ('nbSamples', models.IntegerField(default=0)),
                ('refhops', models.CharField(max_length=1024)),
                ('obshops', models.CharField(max_length=1024)),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihr.ASN')),
            ],
        ),
    ]
