# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-05 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0002_congestion_alarms_forwarding_alarms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forwarding_alarms',
            name='nbSamples',
        ),
        migrations.RemoveField(
            model_name='forwarding_alarms',
            name='obshops',
        ),
        migrations.RemoveField(
            model_name='forwarding_alarms',
            name='refhops',
        ),
        migrations.AddField(
            model_name='forwarding_alarms',
            name='pktDiff',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='forwarding_alarms',
            name='previousHop',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forwarding_alarms',
            name='responsibility',
            field=models.FloatField(default=0.0),
        ),
    ]
