# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-12 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0005_country_disco_events_disco_probes'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='disco_events',
            index_together=set([('streamtype', 'streamname', 'start', 'end')]),
        ),
    ]
