# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-12 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0006_auto_20170612_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco_events',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='disco_events',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
