# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-12 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0009_auto_20170612_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disco_probes',
            old_name='event_id',
            new_name='event',
        ),
    ]
