# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-13 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0011_disco_events_nbdiscoprobes'),
    ]

    operations = [
        migrations.AddField(
            model_name='asn',
            name='disco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asn',
            name='tartiflette',
            field=models.BooleanField(default=True),
        ),
    ]
