# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-13 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0012_auto_20170613_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asn',
            name='tartiflette',
            field=models.BooleanField(default=False),
        ),
    ]
