# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-13 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0013_auto_20170613_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='disco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='tartiflette',
            field=models.BooleanField(default=False),
        ),
    ]
