# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-14 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0014_auto_20170613_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco_events',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
