# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-11 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0015_disco_events_ongoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco_events',
            name='mongoid',
            field=models.CharField(default='000000000000000000000000', max_length=24),
        ),
    ]
