# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-03 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0017_auto_20170711_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco_probes',
            name='ipv4',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AddField(
            model_name='disco_probes',
            name='prefixv4',
            field=models.CharField(default='None', max_length=70),
        ),
    ]
