# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-17 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0020_auto_20170817_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forwarding_alarms_msms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msmid', models.IntegerField(default=0)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msmid', to='ihr.Forwarding_alarms')),
            ],
        ),
        migrations.CreateModel(
            name='Forwarding_alarms_probes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probeid', models.IntegerField(default=0)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probeid', to='ihr.Forwarding_alarms')),
            ],
        ),
    ]
