# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0022_auto_20170817_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delay_alarms_probes',
            name='alarm',
        ),
        migrations.RemoveField(
            model_name='forwarding_alarms_probes',
            name='alarm',
        ),
        migrations.AddField(
            model_name='delay_alarms_msms',
            name='probeid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forwarding_alarms_msms',
            name='probeid',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Delay_alarms_probes',
        ),
        migrations.DeleteModel(
            name='Forwarding_alarms_probes',
        ),
    ]
