# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0023_auto_20170821_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hegemony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timebin', models.DateTimeField(db_index=True)),
                ('hege', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='asn',
            name='ashash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hegemony',
            name='asn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihr.ASN'),
        ),
        migrations.AddField(
            model_name='hegemony',
            name='originasn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_graph', to='ihr.ASN'),
        ),
    ]
