# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0024_auto_20171017_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='hegemony',
            name='af',
            field=models.IntegerField(default=0),
        ),
    ]
