# Generated by Django 2.0.1 on 2018-05-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0027_auto_20180221_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probes_geolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_id', models.IntegerField()),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('level', models.FloatField(default=0.0)),
                ('ipv4', models.CharField(default='None', max_length=64)),
                ('prefixv4', models.CharField(default='None', max_length=70)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihr.Disco_events')),
            ],
        ),
        migrations.AddField(
            model_name='disco_probes',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='disco_probes',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
