# Generated by Django 2.0.9 on 2019-01-16 07:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0029_auto_20180530_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='delay_alarms',
            name='msm_prb_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
