# Generated by Django 2.0.9 on 2019-01-16 07:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0030_delay_alarms_msm_prb_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwarding_alarms',
            name='msm_prb_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
