# Generated by Django 2.0.9 on 2019-06-28 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0031_forwarding_alarms_msm_prb_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atlas_delay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timebin', models.DateTimeField(db_index=True)),
                ('median', models.FloatField(default=0.0)),
                ('nbtracks', models.IntegerField(default=0)),
                ('nbprobes', models.IntegerField(default=0)),
                ('entropy', models.FloatField(default=0.0)),
                ('hop', models.IntegerField(default=0)),
                ('nbrealrtts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Atlas_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=4)),
                ('af', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='delay',
            name='label',
        ),
        migrations.RemoveField(
            model_name='forwarding',
            name='label',
        ),
        migrations.AddField(
            model_name='atlas_delay',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endopint', to='ihr.Atlas_location'),
        ),
        migrations.AddField(
            model_name='atlas_delay',
            name='startpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startpoint', to='ihr.Atlas_location'),
        ),
    ]
