# Generated by Django 2.0.9 on 2019-06-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0032_auto_20190628_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delayranking',
            name='asn',
        ),
        migrations.RemoveField(
            model_name='forwardingranking',
            name='asn',
        ),
        migrations.DeleteModel(
            name='DelayRanking',
        ),
        migrations.DeleteModel(
            name='ForwardingRanking',
        ),
    ]
