# Generated by Django 2.0.9 on 2019-06-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0033_auto_20190628_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delay',
            name='deviation',
        ),
        migrations.RemoveField(
            model_name='forwarding',
            name='resp',
        ),
    ]
