# Generated by Django 2.2.2 on 2019-09-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0036_auto_20190830_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco_events',
            name='streamname',
            field=models.CharField(max_length=128),
        ),
    ]
