# Generated by Django 2.2.2 on 2020-03-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0039_auto_20200312_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihruser',
            name='email',
            field=models.EmailField(help_text='Email of the user, also used a the login ID.', max_length=254, unique=True),
        ),
    ]
