# Generated by Django 2.2.2 on 2020-11-06 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0041_auto_20201105_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hegemony_country',
            old_name='transit_only',
            new_name='transitonly',
        ),
        migrations.RenameField(
            model_name='hegemony_country',
            old_name='weightScheme',
            new_name='weightscheme',
        ),
        migrations.AlterField(
            model_name='hegemony_country',
            name='country',
            field=models.ForeignKey(help_text='Monitored country. Retrieve all dependencies of a country by setting only this parameter and a timebin.', on_delete=django.db.models.deletion.CASCADE, to='ihr.Country'),
        ),
    ]
