# Generated by Django 2.2.27 on 2022-05-10 14:02

import caching.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihr', '0042_auto_20201106_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hegemony_country',
            name='country',
            field=models.ForeignKey(help_text='Monitored country. Retrieve all dependencies of a country by setting only this parameter and a timebin.', on_delete=django.db.models.deletion.CASCADE, to='ihr.Country'),
        ),
        migrations.AlterField(
            model_name='hegemony_country',
            name='hege',
            field=models.FloatField(default=0.0, help_text='AS Hegemony is the estimated fraction of paths towards the monitored country. The values range between 0 and 1, low values represent a small number of path (low dependency) and values close to 1 represent strong dependencies.'),
        ),
        migrations.CreateModel(
            name='Metis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timebin', models.DateTimeField(db_index=True, help_text='Time when the ranking is computed. The ranking uses four weeks of data, e.g., timestamp 1648425600 (2022-03-28T00:00) is based on data from 2022-02-28T00:00 to 2022-03-28T00:00 ')),
                ('metric', models.CharField(help_text='Distance metric used to compute diversity.', max_length=16)),
                ('rank', models.IntegerField(help_text='Selecting all ASes with rank less than equal to 10, gives the 10 most diverse ASes in terms of the selected metric.')),
                ('af', models.IntegerField(help_text='Address Family (IP version), values are either 4 or 6.')),
                ('mean', models.FloatField(default=0.0, help_text='The mean distance value (e.g., AS-path length) we get when using all ASes up to this rank. This decreases with increasing rank, since lower ranks represent closer ASes.')),
                ('asn', models.ForeignKey(help_text="Atlas probes' Autonomous System Number.", on_delete=django.db.models.deletion.CASCADE, to='ihr.ASN')),
            ],
            options={
                'base_manager_name': 'objects',
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Hegemony_prefix',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('timebin', models.DateTimeField(db_index=True, help_text='Timestamp of reported value.')),
                ('prefix', models.CharField(db_index=True, help_text='Monitored prefix (IPv4 or IPv6).', max_length=64)),
                ('hege', models.FloatField(default=0.0, help_text='AS Hegemony is the estimated fraction of paths towards the monitored prefix. The values range between 0 and 1, low values represent a small number of path (low dependency) and values close to 1 represent strong dependencies.')),
                ('af', models.IntegerField(default=0, help_text='Address Family (IP version), values are either 4 or 6.')),
                ('visibility', models.FloatField(default=0.0, help_text='Percentage of BGP peers that see this prefix.')),
                ('rpki_status', models.CharField(help_text='Route origin validation state for the monitored prefix and origin AS using RPKI.', max_length=32)),
                ('irr_status', models.CharField(help_text='Route origin validation state for the monitored prefix and origin AS using IRR.', max_length=32)),
                ('delegated_prefix_status', models.CharField(help_text="Status of the monitored prefix in the RIR's delegated stats. Status other than 'assigned' are usually considered as bogons.", max_length=32)),
                ('delegated_asn_status', models.CharField(help_text="Status of the origin ASN in the RIR's delegated stats. Status other than 'assigned' are usually considered as bogons.", max_length=32)),
                ('descr', models.CharField(help_text='Prefix description from IRR (maximum 64 characters).', max_length=64)),
                ('moas', models.BooleanField(default=False, help_text='True if the prefix is originated by multiple ASNs.')),
                ('asn', models.ForeignKey(help_text='Dependency. Network commonly seen in BGP paths towards monitored prefix.', on_delete=django.db.models.deletion.CASCADE, related_name='prefix_asn', to='ihr.ASN')),
                ('country', models.ForeignKey(help_text="Country for the monitored prefix identified by Maxmind's Geolite2 geolocation database.", on_delete=django.db.models.deletion.CASCADE, to='ihr.Country')),
                ('originasn', models.ForeignKey(help_text='Network seen as originating the monitored prefix.', on_delete=django.db.models.deletion.CASCADE, related_name='prefix_originasn', to='ihr.ASN')),
            ],
            options={
                'base_manager_name': 'objects',
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
    ]
